# Generated by Django 5.1.4 on 2024-12-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=64,
            ),
        ),
    ]
